"""V0-ROL-02: generate each repo's Dependabot config from infra-config's rollers.toml.

For every repo a `tool = "dependabot"` roller covers, this writes two files under
`generated/github/<repo>/`, which are copied into that repo as is:

- `.github/dependabot.yml`: one update entry per roller (ecosystem, directory, cadence, open limit).
- `.github/workflows/qq-roll-land.yml`: lands a clean Dependabot PR through the gate with no human,
  by enabling auto-merge; GitHub merges it only once the required checks pass (D4).

The YAML is written by hand so the output is byte-stable and needs no YAML library.
"""
from __future__ import annotations

import json
from pathlib import Path

from qqroll.config import rollers_for

BACKENDS = {"github"}  # TODO(expert): launchpad, when quirq's own cloud has a dependency updater.
FETCH_METADATA = "25dd0e34f4fe68f24cc83900b1fe3fe149efef98  # v3.1.0"

# rollers.toml cadence -> Dependabot schedule.interval.
INTERVALS = {"daily": "daily", "weekly": "weekly"}
# TODO(expert): "biweekly" has no Dependabot interval; map it to a cron schedule once one is needed.

# The files a clean roll may touch, per ecosystem, relative to the roller's directory. A PR touching
# anything else is not a dependency roll (gate.toml change_class "dependency-roll") and waits for a human.
DEPENDENCY_FILES = {
    "pip": ["requirements*.txt", "pyproject.toml"],
    "npm": ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"],  # workspace: pnpm catalogs
}

HEADER = """\
# GENERATED by quirq-ai/rollers (qqroll dependabot) from quirq-ai/infra-config
# config/rollers.toml at {commit}.
# Do not edit here: change rollers.toml, regenerate in quirq-ai/rollers, and copy.
"""


class GenerateError(Exception):
    pass


def _q(value: str) -> str:
    """A YAML double-quoted scalar. JSON strings are valid YAML double-quoted scalars."""
    return json.dumps(value)


def _rollers(rollers: list[dict], repo: str) -> list[dict]:
    selected = rollers_for(rollers, repo, "dependabot")
    if not selected:
        raise GenerateError(f"{repo}: no dependabot roller in rollers.toml covers this repo")
    for r in selected:
        if r["cadence"] not in INTERVALS:
            raise GenerateError(f"roller {r['name']}: cadence {r['cadence']!r} has no Dependabot interval")
        if r["ecosystem"] not in DEPENDENCY_FILES:
            raise GenerateError(f"roller {r['name']}: ecosystem {r['ecosystem']!r} is not supported")
    return selected


def dependabot_yml(rollers: list[dict], repo: str, commit: str) -> str:
    lines = [HEADER.format(commit=commit).rstrip("\n"), "version: 2", "updates:"]
    for r in _rollers(rollers, repo):
        lines += [
            f"  # roller {r['name']}: {r['moves']}",
            f"  - package-ecosystem: {_q(r['ecosystem'])}",
            f"    directory: {_q(r['directory'])}",
            "    schedule:",
            f"      interval: {_q(INTERVALS[r['cadence']])}",
            f"    open-pull-requests-limit: {int(r['open_limit'])}",
            "    commit-message:",
            f"      prefix: {_q('roll')}",
        ]
    return "\n".join(lines) + "\n"


def _patterns(rollers: list[dict], repo: str) -> list[str]:
    out = []
    for r in _rollers(rollers, repo):
        base = r["directory"].strip("/")
        for name in DEPENDENCY_FILES[r["ecosystem"]]:
            out.append(f"{base}/{name}" if base else name)
    return sorted(set(out))


LAND_WORKFLOW = """\
{header}# Lands a clean Dependabot roll with no human (D4). Clean means: only dependency files changed,
# every commit is Dependabot's and verified, and the bump is not a major version. Auto-merge means
# GitHub merges it only after the required checks pass, so the roll goes through the same gate as
# any change. Anything else, including any failed step, turns auto-merge off and waits for a human.
# Needs, set by an admin: "Allow auto-merge" in the repo settings, and a ruleset that requires the
# gate check on main (V0-ORG-03). Without them auto-merge cannot be enabled and the PR stays open.
# TODO(expert): merges made with GITHUB_TOKEN do not trigger push workflows (post-submit); switch to
# the quirq infra bot's token once it exists. Dependabot PRs only see Dependabot secrets.
# TODO(expert): check how `gh pr merge --auto` behaves once a merge queue is required (V0-ORG-03).
# TODO(suraj): should agents also land major version bumps alone? Default: no, a human lands them.
name: qq-roll-land
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  land:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == {repo_full}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@{fetch_metadata}
      - name: only dependency files, only Dependabot's commits
        id: clean
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR: ${{{{ github.event.pull_request.number }}}}
        run: |
          # Patterns are JSON strings, compared with JSON-encoded filenames, so no name can break a
          # line or a pattern apart. A pattern matches only at its own directory depth.
          allowed=({patterns})
          files=$(gh api --paginate "repos/$GITHUB_REPOSITORY/pulls/$PR/files" --jq '.[].filename | @json')
          others=$(gh api --paginate "repos/$GITHUB_REPOSITORY/pulls/$PR/commits" \\
            --jq '.[] | select(.author.login != "dependabot[bot]" or .commit.verification.verified != true) | .sha')
          clean=true
          if [ -z "$files" ]; then echo "no changed files listed"; clean=false; fi
          if [ -n "$others" ]; then echo "commits not by Dependabot or unverified: $others"; clean=false; fi
          while IFS= read -r f; do
            [ -z "$f" ] && continue
            ok=false
            for p in "${{allowed[@]}}"; do
              [[ "$f" == $p && "${{f//[^\/]/}}" == "${{p//[^\/]/}}" ]] && ok=true
            done
            if [ "$ok" = false ]; then printf 'not a dependency file: %s\\n' "$f"; clean=false; fi
          done <<< "$files"
          echo "clean=$clean" >> "$GITHUB_OUTPUT"
      - name: land through the gate
        id: land
        if: steps.clean.outputs.clean == 'true' && steps.meta.outputs.update-type != 'version-update:semver-major'
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR_URL: ${{{{ github.event.pull_request.html_url }}}}
        run: gh pr merge --auto --squash "$PR_URL"  # TODO(suraj): squash or merge commits (plan §10.3)
      - name: leave anything else to a human
        if: always() && steps.land.outcome != 'success'
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR_URL: ${{{{ github.event.pull_request.html_url }}}}
        run: gh pr merge --disable-auto "$PR_URL" || true  # fails harmlessly when auto-merge is off
"""

def land_workflow(rollers: list[dict], repo: str, commit: str, slug: str | None = None) -> str:
    slug = slug or f"quirq-ai/{repo}"
    patterns = " ".join("'" + json.dumps(p) + "'" for p in _patterns(rollers, repo))
    return LAND_WORKFLOW.format(header=HEADER.format(commit=commit), patterns=patterns,
                                repo_full=f"'{slug}'", fetch_metadata=FETCH_METADATA)


def generate(rollers: list[dict], commit: str, *, backend: str = "github",
             slugs: dict[str, str] | None = None) -> dict[str, str]:
    """Every generated file, keyed by its path under `generated/`.

    `backend` is infra-config's org default_backend; `slugs` maps repo names to owner/name, from
    infra-config repos.toml sources.
    """
    if backend not in BACKENDS:
        raise GenerateError(f"backend {backend!r} has no dependency updater yet")
    repos = sorted({repo for r in rollers if r["tool"] == "dependabot" for repo in r["repos"]})
    files = {}
    for repo in repos:
        base = f"{backend}/{repo}/.github"
        files[f"{base}/dependabot.yml"] = dependabot_yml(rollers, repo, commit)
        files[f"{base}/workflows/qq-roll-land.yml"] = land_workflow(rollers, repo, commit,
                                                                    (slugs or {}).get(repo))
    return files


def github_slugs(cfg: dict) -> dict[str, str]:
    """owner/name for each repo in infra-config repos.toml whose source is on github.com."""
    return {r["name"]: r["source"].removeprefix("github.com/") for r in cfg.get("repos", {}).get("repo", [])
            if r.get("source", "").startswith("github.com/")}


def write(out: Path, files: dict[str, str]) -> None:
    """Write every file, and remove files under `out` that are no longer generated."""
    if out.is_dir():
        for path in [p for p in out.rglob("*") if p.is_file()]:
            if path.relative_to(out).as_posix() not in files:
                path.unlink()
    for rel, text in files.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def check(out: Path, files: dict[str, str]) -> list[str]:
    """Problems with the files under `out`: missing, stale or not generated."""
    problems = []
    for rel, text in sorted(files.items()):
        path = out / rel
        if not path.is_file():
            problems.append(f"{path}: missing; run qqroll dependabot --write")
        elif path.read_text() != text:
            problems.append(f"{path}: stale; run qqroll dependabot --write")
    if out.is_dir():
        for path in sorted(p for p in out.rglob("*") if p.is_file()):
            if path.relative_to(out).as_posix() not in files:
                problems.append(f"{path}: not generated from rollers.toml; remove it")
    return problems
