"""V0-ROL-02: generate each repo's Dependabot config from infra-config's rollers.toml.

For every repo a `tool = "dependabot"` roller covers, this writes two files under
`generated/github/<repo>/`, which are copied into that repo as is:

- `.github/dependabot.yml`: one update entry per roller (ecosystem, directory, cadence, open limit).
- `.github/workflows/qq-roll-land.yml`: lands a clean Dependabot PR through the gate with no human,
  by enabling auto-merge; GitHub merges it only once the required checks pass (D4).

The YAML is written by hand so the output is byte-stable and needs no YAML library.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from qqroll.config import rollers_for

BACKENDS = {"github"}  # TODO(expert): launchpad, when quirq's own cloud has a dependency updater.
FETCH_METADATA = "25dd0e34f4fe68f24cc83900b1fe3fe149efef98  # v3.1.0"

# rollers.toml cadence -> Dependabot schedule.interval.
INTERVALS = {"daily": "daily", "weekly": "weekly"}
# TODO(expert): "biweekly" has no Dependabot interval; map it to a cron schedule once one is needed.

# The files a clean roll may modify, per ecosystem, relative to the roller's directory, and how their
# changed lines are checked (land_check.LINE_RULES). A PR touching anything else is not a dependency
# roll (gate.toml change_class "dependency-roll") and waits for a human. pyproject.toml and
# pnpm-workspace.yaml carry build and script settings, so rolls that edit them wait for a human too.
DEPENDENCY_FILES = {
    "pip": [("requirements*.txt", "pip-requirements")],
    "npm": [("package.json", "npm-manifest"), ("pnpm-lock.yaml", "npm-lock")],
}
LAND_CHECK = Path(__file__).with_name("land_check.py")

HEADER = """\
# GENERATED by quirq-ai/rollers (qqroll dependabot) from quirq-ai/infra-config
# config/rollers.toml at {commit}.
# Do not edit here: change rollers.toml, regenerate in quirq-ai/rollers, and copy.
"""


class GenerateError(Exception):
    pass


def _q(value: str) -> str:
    """A YAML double-quoted scalar. JSON strings are valid YAML double-quoted scalars."""
    return json.dumps(value)


def _rollers(rollers: list[dict], repo: str) -> list[dict]:
    selected = rollers_for(rollers, repo, "dependabot")
    if not selected:
        raise GenerateError(f"{repo}: no dependabot roller in rollers.toml covers this repo")
    for r in selected:
        if r["cadence"] not in INTERVALS:
            raise GenerateError(f"roller {r['name']}: cadence {r['cadence']!r} has no Dependabot interval")
        if r["ecosystem"] not in DEPENDENCY_FILES:
            raise GenerateError(f"roller {r['name']}: ecosystem {r['ecosystem']!r} is not supported")
    return selected


def dependabot_yml(rollers: list[dict], repo: str, commit: str) -> str:
    lines = [HEADER.format(commit=commit).rstrip("\n"), "version: 2", "updates:"]
    for r in _rollers(rollers, repo):
        lines += [
            f"  # roller {r['name']}: {r['moves']}",
            f"  - package-ecosystem: {_q(r['ecosystem'])}",
            f"    directory: {_q(r['directory'])}",
            "    schedule:",
            f"      interval: {_q(INTERVALS[r['cadence']])}",
            f"    open-pull-requests-limit: {int(r['open_limit'])}",
            "    commit-message:",
            f"      prefix: {_q('roll')}",
        ]
    return "\n".join(lines) + "\n"


def _allowed(rollers: list[dict], repo: str) -> list[list[str]]:
    out = []
    for r in _rollers(rollers, repo):
        base = r["directory"].strip("/")
        for name, kind in DEPENDENCY_FILES[r["ecosystem"]]:
            out.append([f"{base}/{name}" if base else name, kind])
    return sorted(out)


LAND_WORKFLOW = """\
{header}# Lands a clean Dependabot roll with no human (D4). The check (quirq-ai/rollers land_check.py, embedded
# below) requires all of: Dependabot opened and last triggered the PR; exactly one commit, made by
# GitHub for Dependabot; only modified dependency files whose changed lines are version lines of the
# bumped dependency, changing only its version numbers (no scripts, index options, URLs, extras or
# non-registry resolutions); a patch or minor bump of one dependency,
# where a 0.x minor counts as major; a gate on the base branch no workflow can fake (a required
# workflow pinned by sha, or a required check bound to an app other than GitHub Actions); and rules on
# the head branch that stop pushes to it after this check (update and non_fast_forward).
# Auto-merge then lands it only after the required checks pass. Anything else, including any failed
# step, turns auto-merge off and leaves the PR to a human.
# Needs, set by an admin: Dependabot version updates on (xo-space is a fork, so the config file alone
# does not turn them on), "Allow auto-merge", a ruleset that requires the gate on main (V0-ORG-03),
# and a ruleset restricting updates and force pushes to dependabot/** with only Dependabot exempt.
# TODO(expert): merges made with GITHUB_TOKEN do not trigger push workflows (post-submit); switch to
# the quirq rollers App's token once it exists. Dependabot PRs only see Dependabot secrets.
# TODO(expert): once owner review is required (V0-GAT-03), decide with gate how dependency-roll skips it.
name: qq-roll-land
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: write
  pull-requests: write
concurrency:  # a newer run cancels an older one; a cancelled run still turns auto-merge off
  group: qq-roll-land-${{{{ github.event.pull_request.number }}}}
  cancel-in-progress: true
jobs:
  land:
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == {repo_full}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - id: meta
        uses: dependabot/fetch-metadata@{fetch_metadata}
      - name: check the roll is clean
        id: clean
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR: ${{{{ github.event.pull_request.number }}}}
          BASE: ${{{{ github.event.pull_request.base.ref }}}}
          HEAD_REF: ${{{{ github.event.pull_request.head.ref }}}}
          SENDER: ${{{{ github.event.sender.login }}}}
          TRIGGER: ${{{{ github.triggering_actor }}}}
          CHANGED: ${{{{ github.event.pull_request.changed_files }}}}
          UPDATE_TYPE: ${{{{ steps.meta.outputs.update-type }}}}
          PREV_VERSION: ${{{{ steps.meta.outputs.previous-version }}}}
          DEP_NAMES: ${{{{ steps.meta.outputs.dependency-names }}}}
          QQ_ALLOWED: '{allowed}'
        run: |
          export QQ_DIR=$(mktemp -d)
          gh api --paginate --slurp "repos/$GITHUB_REPOSITORY/pulls/$PR/files" > "$QQ_DIR/files.json"
          gh api --paginate --slurp "repos/$GITHUB_REPOSITORY/pulls/$PR/commits" > "$QQ_DIR/commits.json"
          gh api --paginate --slurp "repos/$GITHUB_REPOSITORY/rules/branches/$BASE" > "$QQ_DIR/rules.json"
          head=$(jq -rn --arg b "$HEAD_REF" '$b|@uri')
          gh api --paginate --slurp "repos/$GITHUB_REPOSITORY/rules/branches/$head" > "$QQ_DIR/head_rules.json"
          python3 - <<'QQ_LAND_CHECK'
@@LAND_CHECK@@
          QQ_LAND_CHECK
      - name: land through the gate
        id: land
        if: steps.clean.outputs.clean == 'true'
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR_URL: ${{{{ github.event.pull_request.html_url }}}}
          HEAD_SHA: ${{{{ github.event.pull_request.head.sha }}}}
        run: gh pr merge --auto --squash --match-head-commit "$HEAD_SHA" "$PR_URL"  # TODO(suraj): squash or merge commits (plan §10.3)
      - name: leave anything else to a human
        if: always() && steps.land.outcome != 'success'
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR_URL: ${{{{ github.event.pull_request.html_url }}}}
        run: gh pr merge --disable-auto "$PR_URL" || true  # fails harmlessly when auto-merge is off
"""


def land_workflow(rollers: list[dict], repo: str, commit: str, slug: str) -> str:
    allowed = json.dumps(_allowed(rollers, repo), separators=(",", ":"))
    if "'" in allowed:
        raise GenerateError(f"{repo}: a dependency file pattern contains a quote")
    text = LAND_WORKFLOW.format(header=HEADER.format(commit=commit), allowed=allowed,
                                repo_full=f"'{slug}'", fetch_metadata=FETCH_METADATA)
    source = LAND_CHECK.read_text()
    if "${{" in source or "\nQQ_LAND_CHECK" in source:
        raise GenerateError("land_check.py cannot be embedded: it contains an expression or the heredoc end")
    body = "\n".join(("          " + line) if line else "" for line in source.rstrip("\n").split("\n"))
    return with_digest(text.replace("@@LAND_CHECK@@", body))


def with_digest(text: str) -> str:
    """The file with infra-config's `# qq-digest:` line after its header comment.

    Every `.github/workflows/qq-*.yml` in a gated repo must carry one: the presubmit's drift check
    (infra-config qqcfg) hashes the file without that line and fails on a mismatch, so a hand edit to a
    generated workflow is caught.
    """
    if any(line.startswith("# qq-digest: ") for line in text.splitlines()):
        raise GenerateError("a generated workflow already contains a qq-digest line")
    digest = hashlib.sha256(text.encode()).hexdigest()
    lines = text.splitlines(keepends=True)
    at = next(i for i, line in enumerate(lines) if not line.startswith("#"))
    return "".join(lines[:at] + [f"# qq-digest: sha256:{digest}\n"] + lines[at:])


def generate(rollers: list[dict], commit: str, *, backend: str = "github",
             slugs: dict[str, str] | None = None) -> dict[str, str]:
    """Every generated file, keyed by its path under `generated/`.

    `backend` is infra-config's org default_backend; `slugs` maps repo names to owner/name, from
    infra-config repos.toml sources.
    """
    if backend not in BACKENDS:
        raise GenerateError(f"backend {backend!r} has no dependency updater yet")
    repos = sorted({repo for r in rollers if r["tool"] == "dependabot" for repo in r["repos"]})
    files = {}
    for repo in repos:
        base = f"{backend}/{repo}/.github"
        files[f"{base}/dependabot.yml"] = dependabot_yml(rollers, repo, commit)
        if repo not in (slugs or {}):
            raise GenerateError(f"{repo}: not a github.com repo in infra-config repos.toml")
        files[f"{base}/workflows/qq-roll-land.yml"] = land_workflow(rollers, repo, commit, slugs[repo])
    return files


def github_slugs(cfg: dict) -> dict[str, str]:
    """owner/name for each repo in infra-config repos.toml whose source is on github.com."""
    return {r["name"]: r["source"].removeprefix("github.com/") for r in cfg.get("repos", {}).get("repo", [])
            if r.get("source", "").startswith("github.com/")}


def write(out: Path, files: dict[str, str]) -> None:
    """Write every file, and remove files under `out` that are no longer generated."""
    if out.is_dir():
        for path in [p for p in out.rglob("*") if p.is_file()]:
            if path.relative_to(out).as_posix() not in files:
                path.unlink()
    for rel, text in files.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def check(out: Path, files: dict[str, str]) -> list[str]:
    """Problems with the files under `out`: missing, stale or not generated."""
    problems = []
    for rel, text in sorted(files.items()):
        path = out / rel
        if not path.is_file():
            problems.append(f"{path}: missing; run qqroll dependabot --write")
        elif path.read_text() != text:
            problems.append(f"{path}: stale; run qqroll dependabot --write")
    if out.is_dir():
        for path in sorted(p for p in out.rglob("*") if p.is_file()):
            if path.relative_to(out).as_posix() not in files:
                problems.append(f"{path}: not generated from rollers.toml; remove it")
    return problems
